category: user
creator: INTERPOL CNTL
label: Asset listed under US Treasury OFAC Sanctions List
source: https://sanctionslistservice.ofac.treas.gov/api/PublicationPreview/exports/SDN.XML
title: US Treasury OFAC Sanctions List
